ATTACH DATABASE 'db/pre-release.cdb' AS sub;
BEGIN TRANSACTION;
INSERT OR REPLACE INTO datas SELECT * FROM sub.datas;
INSERT OR REPLACE INTO texts SELECT * FROM sub.texts;
COMMIT;
DETACH DATABASE sub;
